name: jwt testing
on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    strategy:
      matrix:
        include:
          - go: '1.19.x'
            os: ubuntu-latest
            canonical: true
          - go: '1.19.x'
            os: windows-latest
            canonical: false

    env:
      GO111MODULE: "on"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}


      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/client9/misspell/cmd/misspell@latest
          go install github.com/wadey/gocovmerge@latest

      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          GO_LIST=$(go list ./...)
          go build
          $(exit $(go fmt $GO_LIST | wc -l))
          go vet $GO_LIST
          which misspell
          find . -type f -name "*.go" | xargs misspell -error -locale US
          staticcheck $GO_LIST
        if: matrix.canonical

      - name: Tests
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          set -e
          mkdir -p cov
          go get -t ./...
          go test -v -race -covermode=atomic -coverprofile=./cov/v1.out -coverpkg=github.com/nats-io/jwt .
          cd v2
          go test -modfile=go_test.mod -v -race -covermode=atomic -coverprofile=../cov/v2.out -coverpkg=github.com/nats-io/jwt/v2 .
          cd ..
          gocovmerge ./cov/*.out > coverage.out
          set +e
        if: matrix.canonical

      - name: Tests (Windows)
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          set -e
          go get -t ./...
          go test -v -race .
          go test -modfile=v2/go_test.mod -v -race .
          set +e
        if: runner.os == 'Windows'

      - name: Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
        if: matrix.canonical
